language: cpp
compiler: gcc
dist: trusty
sudo: required
cache: ccache

env:
  - QT_SELECT=qt4 QMAKE_ARGS=""
  - QT_SELECT=qt4 QMAKE_ARGS="CONFIG+=analytics"
  - QT_SELECT=qt5 QMAKE_ARGS=""
  - QT_SELECT=qt5 QMAKE_ARGS="CONFIG+=analytics"

install:
  - sudo apt-get update -qq
  - if [ "$QT_SELECT" = "qt4" ]; then sudo apt-get install -qq qt4-default; fi
  - if [ "$QT_SELECT" = "qt5" ]; then sudo apt-get install -qq qt5-default qttools5-dev-tools qtdeclarative5-dev qtsystems5-dev; fi

script:
  - qmake $QMAKE_ARGS taot.pro
  - make
